debug: true
database_uri: 'postgresql://localhost/alfred'
secret_key: ''
github:
  client_id: ''
  client_secret: ''
  auth_url: 'https://github.com/login/'
  scopes: 'public_repo'
  authorization_url: 'oauth/authorize'
  token_url: 'oauth/access_token'
beta_users:
  - xobb1t
  - yumike
  - nyumatova
amqp:
  url: 'amqp://guest:guest@localhost:5672/%2F'
  sync_queue_name: 'sync'
